/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class test_Identify */

#ifndef _Included_test_Identify
#define _Included_test_Identify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_Identify
 * Method:    similarity
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_test_Identify_similarity
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
